use utf8;
{
  bots => {
    '@TJOURNAL_WEBHOOK_TAG@' => {
      # test => 1,
      ignore_users => [qw/390471 308880 400974 242158 401272 300996/],
      api_url => 'https://api.tjournal.ru/v1.8',
      list => [
        {
          class => 'ToxicBot',
          user_id => '401824',
          text_match => [qr/\@нейро *токсикъ?\b/i, qr/\@токсикъ?\b/i],
          reply_delay => 5,
          reply_probability => 20,
          api_token => '***', # this and other tokens removed
        },
        {
          class => 'OrlovBot',
          # test => 1,
          user_id => '402224',
          text_match => [
            qr/\bдмитрий +орловъ?\b/i,
            qr/\@орловъ?\b/i,
            qr/\@говнов\b/i,
            qr/\bнейро *орлов[а-я]*\b/i,
            qr/\@jhkjd\b/i,
            qr/\bн+у+\s+и+\s+в+\s+ч+е+м+\s+о+н+а*\s+н+е+\s+п+р+а+в+а*\b/i,
            qr/^\s*ж+а+л+ь+[.,!?1]*\s*$/i,
            qr/^\s*р+а+з+б+а+н+ь+[.,!?1]*\s*$/i,
            qr/^\s*п+о+р+в+а+л+с+я+[\s.,!?1]*ж+а+л+ь+[.,!?1]*\s*$/i,
            qr/\bР+У+С+С+К+И+Е+\b/,
            qr/^[\s\d.,!?]*т+[гр]+а+в+л+я+[\s\d.,!?]*$/i,
            qr/^[\s\d.,!?]*это\s*тебя\s*ебать\s*не\s*должно[\s\d.,!?]*$/i,
            qr/\bпосле[^.]*начался сущий кошмар\b/i,
          ],
          victim_user_id => '398152',
          victim_probability => 33,
          reply_delay => 5,
          reply_probability => 90, #90,
          api_token => '***',
        },
        (map { +{
          class => 'OrlovBot',
          user_id => $_,
          api_token => '***',
        } } qw/308701 383405 283343 322943/),
        {
          class => 'PorfirevichBot',
          # test => 1,
          text_match => [qr/\@порфирьевичъ?\b/i],
          user_id => '402353',
          api_token => '***',
          retries => 2,
          length => 90,
        },
        {
          class => 'RuGPT3Bot',
          text_match => [qr/\@(ru)? *gpt\-?3( *bot)?\b/i],
          user_id => '404237',
          api_token => '***',
        },
        {
          class => 'YesNoMaybeBot',
          user_id => '402512',
          text_match => [
            qr/\@нужен *ответ\b/i,
            qr/\@нейро *ответ\b/i,
            # qr/\@о+т+в+е+т+ь*\b/i,
            qr/^\s*п+р+а+в+д+а+\s*\?[.,!?1]*\s*$/i,
            # qr/^\s*с+т+о+и+т+\s*\?[.,!?1]*\s*$/i,
            # qr/^\s*н+а+д+о+\s*\?[.,!?1]*\s*$/i,
          ],
          api_token => '***',
        },
        {
          class => 'WhenBot',
          text_match => [qr/^\s*к+о+г+д+а+\s*\?[.,!?1]*\s*$/i],
          api_token => '***',
        },
        {
          class => 'DonBot',
          # test => 1,
          text_match => [
            qr/\@д+о+н+\s*б+о+т+\b/i,
            qr/^\s*и+з+в+и+н+и+с+ь*[.,!?1]*\s*$/i
          ],
          user_id => '403321',
          api_token => '***',
        },
        {
          class => 'BalabobaBot',
          user_id => '406755',
          text_match => [qr/\s*\@б+а+л+а+б+о+б+а+\b/i],
          api_token => '***',
        },
        {
          class => 'WhoIsBot',
          # test => 1,
          victim_user_id => '271058',
          victim_probability => 100,
          tag => '@TJOURNAL_WEBHOOK_TAG@',
          text_match => [qr/\@[кх]+т+о+\s*э+т+о+\b/i],
          api_token => '***',
        },
        {
          class => 'WhoAmBot',
          # test => 1,
          tag => '@TJOURNAL_WEBHOOK_TAG@',
          text_match => [qr/\@[кх]+т+о+\s*я+\b/i],
          api_token => '***',
        },

        (map { +{
          class => 'DynyaBot',
          # test => 1,
          user_id => $_,
          reply_delay => 5,
          api_token => '***',
        } } qw/336114/),
        {
          class => 'DynyaBot',
          # test => 1,
          text_match => [
            qr/\b\@д+ы+н+я+\b/i,
            qr/\bнейро *дын[а-я]*\b/i,
          ],
          reply_delay => 5,
          reply_probability => 90,
          text_match_probability => 100,
          like_probability => 10,
          user_id => '445812',
          api_token => '***',
        },
        {
          class => 'DynyaBot',
          # test => 1,
          text_match => [
            # qr/^[\s\d.,!?]*\@?согласен[\s\d.,!?]*$/i,
            qr/^[\s\d.,!?]*р+о+т+\s*з+а+к+р+о+й+[\s\d.,!?]*$/i,
            qr/^[\s\d.,!?]*з+а+к+р+о+й+\s*р+о+т+[\s\d.,!?]*$/i,
            # qr/\[\@307570\|согласен\]/i,
          ],
          reply_delay => 5,
          like_probability => 30,
          text_match_probability => 50,
          api_token => '***',
        },
      ],
    },
  },
  mojo => {
    secrets => ['Let\'s not be so obvious'],
    hypnotoad => {
      'listen'                => ['http://@HTTPD_BIND@'],
      # 'proxy'                 => 1,
      'workers'               => 5,
      'pid_file'              => '@PID_FILE@',
      'heartbeat_timeout'     => 60,
      'inactivity_timeout'    => 60,
      'multi_accept'          => 32,
      'clients'               => 10,
      'accepts'               => 1024,
      # 'requests'              => 128,
    },
  },
};
